AllCops:
  Exclude:
    - "Guardfile"
    - "Gemfile"
    - "homework_tester/**/*"
    - "test/**/*"
    - "config/**/*"
    - "spec/**/*"
    - "bin/**/*"
    - "db/schema.rb"
Documentation:
  Enabled: false
