# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26713f4d26e3f5281aef9d0ef1dd385648affa4620ada03d92ed85a3d2c3fc8b56dbdc2f17b0a80de0cb9dea2e21215db3210f54a7deef98cbc228aacb213370

test:
  secret_key_base: c691f4a13f6248f62e339ec8d9bd20558155d47c7235cb7aa135924be558774424bc30796dde217b56f0c043dee7b521515fd73c7a23841e6654b3a63c545f96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
